language: node_js
sudo: required
services:
  - docker

before_install:
  - docker build -t thanhnd/docker-react -f Dockerfile.dev .

script:
  - docker run thanhnd/docker-react npm run test -- --coverage